[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  included_files = ["api/script.js", "api/fu.wasm"]

[[redirects]]
  from = "/api"
  to = "/.netlify/functions/api"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api"
  status = 200
