[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  included_files = ["netlify/functions/script.js", "api/stream-token.wasm"]

[[redirects]]
  from = "/api"
  to = "/.netlify/functions/api"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api"
  status = 200
